/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface ConfigSchema {
  /**
   * The hostname to host the server on.
   */
  hostname?: string;
  /**
   * The port to host the server on.
   */
  port?: number;
  [k: string]: unknown;
}
